# Generated by Django 2.2.3 on 2020-03-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/img/person.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
