# Generated by Django 2.2.3 on 2020-03-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200325_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='/static/img/person.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
