# Generated by Django 2.2.3 on 2020-04-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200329_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='من حال نداشتم این قسمت رو پر کنم.'),
        ),
    ]
