# Generated by Django 2.2.3 on 2020-06-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200415_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='من حال نداشتم این قسمت رو پر کنم.', null=True),
        ),
    ]
