# Generated by Django 2.2.3 on 2020-05-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20200515_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(default='/static/img/person.jpg'),
        ),
    ]
