# Generated by Django 2.2.3 on 2020-06-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_auto_20200602_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filter',
            field=models.CharField(default='', max_length=60),
        ),
    ]
