# Generated by Django 2.2.3 on 2020-06-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20200604_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
