# Generated by Django 2.2.3 on 2020-06-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_auto_20200611_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='display',
            field=models.CharField(default='block', max_length=60),
        ),
    ]
